# Generated by Django 5.0.7 on 2024-07-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField(null=True)),
                ('defender_card', models.IntegerField(null=True)),
                ('attacker_score', models.IntegerField(default=0)),
                ('defender_score', models.IntegerField(default=0)),
                ('win_condition', models.CharField(choices=[('HIGH', 'Higher number wins'), ('LOW', 'Lower number wins')], max_length=4, null=True)),
                ('status', models.CharField(choices=[('PENDING', '반격 대기'), ('ONGOING', '게임 진행 중'), ('FINISHED', '게임 종료'), ('CANCELLED', '취소')], default='PENDING', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('ATTACKER_WIN', 'Attacker Win'), ('DEFENDER_WIN', 'Defender Win'), ('DRAW', 'Draw')], max_length=20, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
